/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_BSMpartIIExtension_H_
#define	_BSMpartIIExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleSafetyExtensions.h"
#include "SpecialVehicleExtensions.h"
#include "VehicleDummyStruct.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BSMpartIIExtension_PR {
	BSMpartIIExtension_PR_NOTHING,	/* No components present */
	BSMpartIIExtension_PR_vehicleSafetyExt,
	BSMpartIIExtension_PR_specialVehicleExt,
	BSMpartIIExtension_PR_vehicleDummySt1,
	BSMpartIIExtension_PR_vehicleDummySt2,
	BSMpartIIExtension_PR_vehicleDummySt3,
	BSMpartIIExtension_PR_vehicleDummySt4,
	BSMpartIIExtension_PR_vehicleDummySt5,
	BSMpartIIExtension_PR_vehicleDummySt6,
	BSMpartIIExtension_PR_vehicleDummySt7,
	BSMpartIIExtension_PR_vehicleDummySt8,
	BSMpartIIExtension_PR_vehicleDummySt9,
	BSMpartIIExtension_PR_vehicleDummySt10,
	BSMpartIIExtension_PR_vehicleDummySt11,
	BSMpartIIExtension_PR_vehicleDummySt12,
	BSMpartIIExtension_PR_vehicleDummySt13,
	BSMpartIIExtension_PR_vehicleDummySt14,
	BSMpartIIExtension_PR_vehicleDummySt15,
	BSMpartIIExtension_PR_vehicleDummySt16,
	BSMpartIIExtension_PR_vehicleDummySt17,
	BSMpartIIExtension_PR_vehicleDummySt18,
	BSMpartIIExtension_PR_vehicleDummySt19,
	BSMpartIIExtension_PR_vehicleDummySt20,
	BSMpartIIExtension_PR_vehicleDummySt21,
	BSMpartIIExtension_PR_vehicleDummySt22,
	BSMpartIIExtension_PR_vehicleDummySt23,
	BSMpartIIExtension_PR_vehicleDummySt24,
	BSMpartIIExtension_PR_vehicleDummySt25,
	BSMpartIIExtension_PR_vehicleDummySt26,
	BSMpartIIExtension_PR_vehicleDummySt27,
	BSMpartIIExtension_PR_vehicleDummySt28,
	BSMpartIIExtension_PR_vehicleDummySt29,
	BSMpartIIExtension_PR_vehicleDummySt30,
	BSMpartIIExtension_PR_vehicleDummySt31,
	BSMpartIIExtension_PR_vehicleDummySt32,
	BSMpartIIExtension_PR_vehicleDummySt33,
	BSMpartIIExtension_PR_vehicleDummySt34,
	BSMpartIIExtension_PR_vehicleDummySt35,
	BSMpartIIExtension_PR_vehicleDummySt36,
	BSMpartIIExtension_PR_vehicleDummySt37,
	BSMpartIIExtension_PR_vehicleDummySt38,
	BSMpartIIExtension_PR_vehicleDummySt39,
	BSMpartIIExtension_PR_vehicleDummySt40,
	BSMpartIIExtension_PR_vehicleDummySt51,
	BSMpartIIExtension_PR_vehicleDummySt52,
	BSMpartIIExtension_PR_vehicleDummySt53,
	BSMpartIIExtension_PR_vehicleDummySt54,
	BSMpartIIExtension_PR_vehicleDummySt55,
	BSMpartIIExtension_PR_vehicleDummySt56,
	BSMpartIIExtension_PR_vehicleDummySt57,
	BSMpartIIExtension_PR_vehicleDummySt58,
	BSMpartIIExtension_PR_vehicleDummySt59,
	BSMpartIIExtension_PR_vehicleDummySt60,
	BSMpartIIExtension_PR_vehicleDummySt61
} BSMpartIIExtension_PR;

/* BSMpartIIExtension */
typedef struct BSMpartIIExtension {
	BSMpartIIExtension_PR present;
	union BSMpartIIExtension_u {
		VehicleSafetyExtensions_t	 vehicleSafetyExt;
		SpecialVehicleExtensions_t	 specialVehicleExt;
		VehicleDummyStruct_t	 vehicleDummySt1;
		VehicleDummyStruct_t	 vehicleDummySt2;
		VehicleDummyStruct_t	 vehicleDummySt3;
		VehicleDummyStruct_t	 vehicleDummySt4;
		VehicleDummyStruct_t	 vehicleDummySt5;
		VehicleDummyStruct_t	 vehicleDummySt6;
		VehicleDummyStruct_t	 vehicleDummySt7;
		VehicleDummyStruct_t	 vehicleDummySt8;
		VehicleDummyStruct_t	 vehicleDummySt9;
		VehicleDummyStruct_t	 vehicleDummySt10;
		VehicleDummyStruct_t	 vehicleDummySt11;
		VehicleDummyStruct_t	 vehicleDummySt12;
		VehicleDummyStruct_t	 vehicleDummySt13;
		VehicleDummyStruct_t	 vehicleDummySt14;
		VehicleDummyStruct_t	 vehicleDummySt15;
		VehicleDummyStruct_t	 vehicleDummySt16;
		VehicleDummyStruct_t	 vehicleDummySt17;
		VehicleDummyStruct_t	 vehicleDummySt18;
		VehicleDummyStruct_t	 vehicleDummySt19;
		VehicleDummyStruct_t	 vehicleDummySt20;
		VehicleDummyStruct_t	 vehicleDummySt21;
		VehicleDummyStruct_t	 vehicleDummySt22;
		VehicleDummyStruct_t	 vehicleDummySt23;
		VehicleDummyStruct_t	 vehicleDummySt24;
		VehicleDummyStruct_t	 vehicleDummySt25;
		VehicleDummyStruct_t	 vehicleDummySt26;
		VehicleDummyStruct_t	 vehicleDummySt27;
		VehicleDummyStruct_t	 vehicleDummySt28;
		VehicleDummyStruct_t	 vehicleDummySt29;
		VehicleDummyStruct_t	 vehicleDummySt30;
		VehicleDummyStruct_t	 vehicleDummySt31;
		VehicleDummyStruct_t	 vehicleDummySt32;
		VehicleDummyStruct_t	 vehicleDummySt33;
		VehicleDummyStruct_t	 vehicleDummySt34;
		VehicleDummyStruct_t	 vehicleDummySt35;
		VehicleDummyStruct_t	 vehicleDummySt36;
		VehicleDummyStruct_t	 vehicleDummySt37;
		VehicleDummyStruct_t	 vehicleDummySt38;
		VehicleDummyStruct_t	 vehicleDummySt39;
		VehicleDummyStruct_t	 vehicleDummySt40;
		VehicleDummyStruct_t	 vehicleDummySt51;
		VehicleDummyStruct_t	 vehicleDummySt52;
		VehicleDummyStruct_t	 vehicleDummySt53;
		VehicleDummyStruct_t	 vehicleDummySt54;
		VehicleDummyStruct_t	 vehicleDummySt55;
		VehicleDummyStruct_t	 vehicleDummySt56;
		VehicleDummyStruct_t	 vehicleDummySt57;
		VehicleDummyStruct_t	 vehicleDummySt58;
		VehicleDummyStruct_t	 vehicleDummySt59;
		VehicleDummyStruct_t	 vehicleDummySt60;
		VehicleDummyStruct_t	 vehicleDummySt61;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BSMpartIIExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BSMpartIIExtension;

#ifdef __cplusplus
}
#endif

#endif	/* _BSMpartIIExtension_H_ */
#include <asn_internal.h>
