/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_PartIIid_H_
#define	_PartIIid_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PartIIid */
typedef long	 PartIIid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartIIid;
asn_struct_free_f PartIIid_free;
asn_struct_print_f PartIIid_print;
asn_constr_check_f PartIIid_constraint;
ber_type_decoder_f PartIIid_decode_ber;
der_type_encoder_f PartIIid_encode_der;
xer_type_decoder_f PartIIid_decode_xer;
xer_type_encoder_f PartIIid_encode_xer;
per_type_decoder_f PartIIid_decode_uper;
per_type_encoder_f PartIIid_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PartIIid_H_ */
#include <asn_internal.h>
