/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_SpecialVehicleExtensions_H_
#define	_SpecialVehicleExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleEventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpecialVehicleExtensions */
typedef struct SpecialVehicleExtensions {
	VehicleEventFlags_t	*events	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpecialVehicleExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpecialVehicleExtensions;

#ifdef __cplusplus
}
#endif

#endif	/* _SpecialVehicleExtensions_H_ */
#include <asn_internal.h>
