/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_VehicleDummyStruct_H_
#define	_VehicleDummyStruct_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleEventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathHistory;

/* VehicleDummyStruct */
typedef struct VehicleDummyStruct {
	VehicleEventFlags_t	*events	/* OPTIONAL */;
	struct PathHistory	*pathHistory	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleDummyStruct_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleDummyStruct;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PathHistory.h"

#endif	/* _VehicleDummyStruct_H_ */
#include <asn_internal.h>
